name: CD
on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types: [completed]
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          workflow_conclusion: success
          name: build
          path: .
          
      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          
      - name: Deploy
        env:
          DEPLOY_PATH: /home/${{ secrets.USERNAME }}/Server
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "mkdir -p $DEPLOY_PATH"
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "rm -rf $DEPLOY_PATH/*"
          scp -r ./* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:$DEPLOY_PATH/
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd $DEPLOY_PATH && npm install && chmod -R 755 . && npx prisma generate && pm2 restart kanban-backend || pm2 start npm --name 'kanban-backend' -- start"